version: '3.4'

services:

  wcas-gui:
    build:
      context: .
    image: wcas-gui
    container_name: "${APP_CONTAINER_NAME}"
    ports:
      - "${APP_CONTAINER_PORT}:80"
    env_file:
      - .env
